/* THIS CODE IS MY OWN WORK, IT WAS WRITTEN WITHOUT CONSULTING A TUTOR OR CODE WRITTEN BY OTHER STUDENTS - Naomi Keusch Baker */
SELECT DISTINCT pnum
FROM part
WHERE color = 'Red'
AND city = 'London'
